# Generated by Django 4.2.11 on 2025-07-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0002_department_employee_email_employee_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('age_in_weeks', models.PositiveIntegerField()),
                ('purpose', models.CharField(choices=[('meat', 'Meat'), ('eggs', 'Eggs')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FishPond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pond_name', models.CharField(max_length=100)),
                ('fish_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PigPen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pigs', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('trip_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('taxi', 'Taxi'), ('lorry', 'Lorry')], max_length=10)),
                ('plate_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default='unassign'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_app.department'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_app.vehicle'),
        ),
        migrations.AddField(
            model_name='pigpen',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_app.department'),
        ),
        migrations.AddField(
            model_name='fishpond',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_app.department'),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_app.department'),
        ),
        migrations.AddField(
            model_name='chickenbatch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_app.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office_app.company'),
        ),
    ]
